language: perl

perl:
   - "blead"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"

env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - sudo apt-get update
  - sudo apt-get install graphviz graphviz-dev
  - cpan-install GraphViz2 ExtUtils::MakeMaker~6.68 --deps

script:
  - perl Build.PL
    # -Wno-strict-aliasing as the check causes issues on Perl 5.14 builds
  - CFLAGS="-Wall -Wextra -Werror -Wno-strict-aliasing" ./Build
  - prove -br -j$(test-jobs) $(test-files)

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
