language: perl

perl:
   - "blead"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"

env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - sudo apt-get update
  - sudo apt-get install graphviz graphviz-dev
  - cpan-install GraphViz2 ExtUtils::MakeMaker~6.68 --deps

script:
  - perl Build.PL
    # -Wno-strict-aliasing as the check causes issues on Perl 5.14 builds
  - CFLAGS="-Wall -Wextra -Werror -Wno-strict-aliasing" ./Build
  - prove -br -j$(test-jobs) $(test-files)

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always

env:
  global:
   - secure: "beuMUf7wSPXanIo6TjHG+6bY4XwFKbFXwnmZsP93CulXAfm8is72uJsT58bIPGwH8dqgm5W+D6EsL+ai91QTbsxUUvMpZpjLnfdyKOSLinS9I9/0ydRK2OftU34Er9unqYIq+2X+SncXIAqQUvRpEoijR2zFa/uplG6UoWaiAes="

addons:
  coverity_scan:
    project:
      name: "maxmind/MaxMind-DB-Writer-perl"
      description: "MMDB writer"
    notification_email: dev@maxmind.com
    build_command_prepend: "perl Build.PL; ./Build clean"
    build_command:   "./Build"
    branch_pattern: .*coverity.*
