language: perl

perl:
   - "blead"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"

env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1

before_install:
  - git clone git://github.com/haarg/perl-travis-helper ~/perl-travis-helper
  - source ~/perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - sudo apt-get update
  - sudo apt-get install graphviz-dev
  - cpan-install GraphViz2
  - git clone --branch=master git://github.com/maxmind/MaxMind-DB-Common-perl.git common
  - cd common
  - "dzil authordeps --missing | xargs -n 5 -P 10 cpanm --quiet --notest"
  - "dzil listdeps --missing  | grep -v MaxMind::DB | cpanm --quiet --notest"
  - dzil install --install-comman "cpanm --quiet --notest ."
  - cd ..
  - git clone --branch=master git://github.com/maxmind/MaxMind-DB-Reader-perl.git reader
  - cd reader
  - "dzil authordeps --missing | xargs -n 5 -P 10 cpanm --quiet --notest"
  - "dzil listdeps --missing  | grep -v MaxMind::DB | cpanm --quiet --notest"
  - dzil install --install-comman "cpanm --quiet --notest ."
  - cd ..
  - "dzil authordeps --missing | xargs -n 5 -P 10 cpanm --quiet --notest"
  - "dzil listdeps --missing | grep -v MaxMind::DB | cpanm --quiet --notest"

script:
  - perl Makefile.PL
  - make
  - prove -br -j$(test-jobs) $(test-files)

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
